### ISSUE TITLE
Websocket does not forward Ping

### ISSUE THREAD

**Issue by crholm** [vulcand/oxy#150]
Hi, it seams that oxy does not forward some control messages but rather use gorilla/websocket defaults in handling message types such as Ping (code 9), Pong (code 10)

https://github.com/vulcand/oxy/blob/a3ed5f65204f4ffccbb56d58cec466cdb7ab730b/forward/fwd.go#L399
Only really reads Text (code 1) or Binary (code 2)

https://github.com/gorilla/websocket/blob/master/conn.go#L944
Pings and Pongs are discarded, since gorilla uses a specific callback for this type of control messages.

Is there any particular reason for letting the proxy answer Ping/Pong messages? instead of the destination.

**Comment by HenrikHolst** [comment]
A major implication of this issue is that clients using Ping frames to determine service availability will in reality only see the proxy availability forcing services to implement protocol level ping/pong messages to handle what the ping/pong frames are designed to solve.

In other words, not forwarding these frames makes any proxy using oxy a non-transparent proxy.

**Comment by maximusfloydus** [comment]
This issue caused us not to be able to use Traefik our web socket services.

**Comment by crholm** [comment]
We are facing the same thing. Wanting to use traefik, but this might be a showstopper for us as well. One can of course work around it, but it seams like it is something that really should be fixed

**Comment by crholm** [comment]
Closing issue since merge of pull request.
